title: BSG 9432
email: bsg9432@gmail.com
description: A FIRST Robotics team in Menifee, CA
baseurl: "" # Don't change this, this refers to the site's relative path, like /blog.
url: "http://bsg9432.github.io"
#twitter_username: Robotics1418
github_username: bsg9432
#facebook_username: robotics1418

# Build settings
sass:
    style: compressed
exclude:
    - README.md
    - LICENSE.md
    - CNAME
    - Gemfile
    - Gemfile.lock
    - package.json
    - vendor
    - vendor/cache
    - ruby
    - .bundle
include:
    - _pages
plugins:
    - octopress-autoprefixer
